In [1]:
import numpy as np

In [2]:
type([1,2,3])

list

In [5]:
arreglo_np = np.array([1,2,3])

In [6]:
type(arreglo_np)

numpy.ndarray

In [8]:
tupla_np = np.array([1,2,3,4])

In [9]:
type(tupla_np)

numpy.ndarray

In [11]:
np.zeros((1))

array([0.])

In [12]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.zeros((5,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [17]:
np.zeros([5,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
np.empty((3,4,5))

array([[[ 1.21628272e+200,  1.04145949e-152,  2.42766851e-154,
          7.13637444e+159,  2.05130604e+161],
        [ 1.91084237e+214,  2.09569046e-110,  7.04142211e-009,
          4.27255707e+180,  1.12958003e+277],
        [ 2.20892687e+161,  5.98147383e-154,  1.02184935e-152,
          6.09223075e+247,  5.77094692e-114],
        [ 1.05016929e-153,  3.75583054e+233,  1.02420533e-259,
          2.25563609e-153,  1.39439370e-258]],

       [[ 6.32300944e+233,  7.21618999e-067,  6.01346953e-154,
          3.98220432e+209, -3.38460737e+125],
        [ 3.65085442e+233,  1.33360322e+241,  1.79128028e-280,
          6.75617319e+173,  9.07236106e+242],
        [ 4.42436122e-310,  6.04608850e-138,  8.73990339e+245,
          1.28431263e-303,  1.14947120e-316],
        [ 2.05226842e-289,  8.73990206e+245,  7.46693490e-301,
          5.01298974e-292,  2.13450445e-287]],

       [[ 1.63468168e-301,  2.21755102e-296,  4.22893062e-307,
          1.62598149e-260,  7.52714526e+252],
        [ 4.238

In [20]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
np.arange(3,10) #[3,10[ #1

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,20,2) #[3,10[ #2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])