In [1]:
import numpy as np

In [2]:
paises_uno = ('Ecuador', 'USA', 'Cuba','Venezuela')

In [3]:
paises_dos = ('Brasil', 'China', 'Japon','Mexico')

In [4]:
arreglo_paises_2d = np.array([paises_uno,paises_dos])

In [5]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brasil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [6]:
arreglo_paises_2d.shape # (dimension, elementos x dimension)
# Shape indica el número de dimensiones que tiene el arreglo

(2, 4)

In [7]:
arreglo_paises_2d.flatten() # aplanado de dimensiones

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brasil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [9]:
arreglo_paises_2d.flatten().shape

(8,)

In [10]:
arreglo_paises_2d.flatten().reshape(2,2,2) #Reshape permite redimensionar el arreglo

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brasil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [11]:
arreglo_paises_2d.flatten().reshape(4,-1) #Permite reajustar el areglo a lo que alcance a llenar con el -1, 
#el -1 autocalcula la dimension

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brasil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [13]:
arreglo_paises_2d.flatten().reshape(-1,2)

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brasil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [14]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brasil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [15]:
arreglo_paises_2d.T #el T permite hacer una transpuesta

array([['Ecuador', 'Brasil'],
       ['USA', 'China'],
       ['Cuba', 'Japon'],
       ['Venezuela', 'Mexico']], dtype='<U9')

In [16]:
arreglo_paises_2d.T.shape

(4, 2)

In [17]:
arreglo_paises_2d.T.flatten()

array(['Ecuador', 'Brasil', 'USA', 'China', 'Cuba', 'Japon', 'Venezuela',
       'Mexico'], dtype='<U9')

In [18]:
# SPLITS - permite seccionar al arreglo de alguna manera , en otros arreglos

In [19]:
arreglo_paises = arreglo_paises_2d.T.flatten()

In [20]:
arreglo_paises

array(['Ecuador', 'Brasil', 'USA', 'China', 'Cuba', 'Japon', 'Venezuela',
       'Mexico'], dtype='<U9')

In [21]:
np.split(arreglo_paises,2)#(Arreglo, #de partes)

[array(['Ecuador', 'Brasil', 'USA', 'China'], dtype='<U9'),
 array(['Cuba', 'Japon', 'Venezuela', 'Mexico'], dtype='<U9')]

In [22]:
np.split(arreglo_paises,4)

[array(['Ecuador', 'Brasil'], dtype='<U9'),
 array(['USA', 'China'], dtype='<U9'),
 array(['Cuba', 'Japon'], dtype='<U9'),
 array(['Venezuela', 'Mexico'], dtype='<U9')]

In [23]:
arreglo = np.arange(12)

In [24]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
np.split(arreglo,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [26]:
np.split(arreglo,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [27]:
np.split(arreglo,6)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

In [28]:
np.split(arreglo,[1,3,5,7,9]) #Enviar un nuevo arreglo como argumento permite dividir
# de acuerdo al índice en el cual se quiere realizar el split

[array([0]),
 array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10, 11])]

In [32]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brasil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [35]:
#Splitting Horizontal
np.hsplit(arreglo_paises_2d,2)

[array([['Ecuador', 'USA'],
        ['Brasil', 'China']], dtype='<U9'), array([['Cuba', 'Venezuela'],
        ['Japon', 'Mexico']], dtype='<U9')]

In [37]:
arr1,arr2,arr3,arr4 = np.hsplit(arreglo_paises_2d,4)

In [38]:
arr1

array([['Ecuador'],
       ['Brasil']], dtype='<U9')

In [39]:
arr2

array([['USA'],
       ['China']], dtype='<U9')

In [40]:
arr3

array([['Cuba'],
       ['Japon']], dtype='<U9')

In [41]:
arr4

array([['Venezuela'],
       ['Mexico']], dtype='<U9')

In [ ]:
#Splitting Vertical
np.vsplit(arreglo_paises_2d,2)

In [42]:
type(np.hsplit(arreglo_paises_2d,4))

list

In [43]:
x1,x2,x3 = [1,2,3]

In [44]:
x1

1

In [45]:
x2

2

In [46]:
x3

3