# Indices

In [2]:
import numpy as np

In [3]:
numeros = np.arange(11)**2

In [4]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
indices = [2,5,7]

In [6]:
numeros[indices]

array([ 4, 25, 49], dtype=int32)

In [7]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia']
])

In [8]:
arreglo_frutas.shape

(3, 4)

In [9]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2]
]) #Indices de las filas

In [10]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2]
])#Indices de las columnas

In [14]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [15]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [16]:
filas_ex= np.array([
    [0,0],
    [1,1],
    [2,2]
])

In [17]:
columnas_ex =np.array([
    [2,3],
    [2,3],
    [2,3]
])

In [18]:
arreglo_frutas[filas_ex,columnas_ex]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandia']], dtype='<U10')

In [19]:
arreglo_frutas3d = np.arange(24).reshape(4,3,2)

In [20]:
arreglo_frutas3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [30]:
arreglo_frutas3d = np.array([
    [['Piña','Manzana'],
     ['Pera','Melon'],
     ['Uvilla','Durazno']],
    
    [['Pera','Uva'],
     ['Naranja','Papaya'],
     ['Coco','Cereza']],
     
    [['Frutilla','Platano'],
     ['Granadilla','Sandia'],
     ['Tamarindo','Toronja']]
])

In [31]:
arreglo_frutas3d

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Uvilla', 'Durazno']],

       [['Pera', 'Uva'],
        ['Naranja', 'Papaya'],
        ['Coco', 'Cereza']],

       [['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Tamarindo', 'Toronja']]], dtype='<U10')

In [46]:
arreglox= np.array([
    [0,0,3],
    [0,0,2]
    
])
arregloy = np.array([
    [0,0,2],
    [0,0,2]
])
arregloz = np.array([
    [0,0,1],
    [0,0,1]
])

In [47]:
arreglo_frutas3d[,arregloy,arregloz]

TypeError: list indices must be integers or slices, not tuple

In [41]:
arreglo_frutas3d

[array([[0, 3]]), array([[0, 2]]), array([[0, 1]])]

In [55]:
frutas1d = arreglo_frutas.flatten()

In [56]:
frutas1d

array(['Piña', 'Manzana', 'Pera', 'Melon', 'Uvilla', 'Durazno', 'Pera',
       'Uva', 'Naranja', 'Papaya', 'Coco', 'Cereza', 'Frutilla',
       'Platano', 'Granadilla', 'Sandia', 'Tamarindo', 'Toronja'],
      dtype='<U10')

In [60]:
for fruta in frutas1d:
    if fruta.startsWith('P'):
        fruta

AttributeError: 'numpy.ndarray' object has no attribute 'toList'